name: Publish

on:
  push:
    branches:
      - main

concurrency:
  group: publish
  cancel-in-progress: false

jobs:
  publish:
    name: Version and publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: node ./upm install --frozen-lockfile

      - name: Version and publish packages
        run: npm run release:check && npm run tegami ci
        env:
          GITHUB_TOKEN: ${{ github.token }}
